name: Deploy Terraform AWS

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Infraestrutura AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Inicializar Terraform
        run: terraform init

      - name: Verificar formatação
        run: terraform fmt -check

      - name: Validar configuração
        run: terraform validate

      - name: Gerar plano de execução
        run: terraform plan -out=tfplan

      - name: Salvar plano como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

      - name: Aplicar infraestrutura
        run: terraform apply -auto-approve tfplan